import { IRaceDefaults } from '../../interfaces';

export const AUSIE_DEFAULTS: IRaceDefaults = {
  value: {
    power: 40,
    intellect: 65,
    attentiveness: 70,
    learnability: 40,
    agility: 40,
    empathy: 60,
    regeneration: 25,
    health: 23,
    lifespan: 15,
    childhoodLength: 70,
    memory: 45,
    bodyType: 50,
    behaviorTrend: 55,
    proactivity: 60,
    knowledgeChannel: 50,
    willPower: 50,
    curiosity: 45,
    analysis: 55,
    emotionality: 30,
    greed: 20,
    libido: 50,
    aggressiveness: 13,
    gaiety: 60,
    moralStandards: 60,
    luck: 51,
  },
  delta: {
    power: 2,
    intellect: 2,
    attentiveness: 3,
    learnability: 5,
    agility: 3,
    empathy: 3,
    regeneration: 2,
    health: 2,
    lifespan: 2,
    childhoodLength: 5,
    memory: 5,
    bodyType: 15,
    behaviorTrend: 20,
    proactivity: 10,
    knowledgeChannel: 15,
    willPower: 10,
    curiosity: 15,
    analysis: 20,
    emotionality: 15,
    greed: 7,
    libido: 10,
    aggressiveness: 3,
    gaiety: 15,
    moralStandards: 8,
    luck: 2,
  },
};
