import { IRaceDefaults } from '../../interfaces';

export const HIGH_DEFAULTS: IRaceDefaults = {
  value: {
    power: 23,
    intellect: 70,
    attentiveness: 75,
    learnability: 55,
    agility: 55,
    empathy: 55,
    regeneration: 12,
    health: 33,
    lifespan: 72,
    childhoodLength: 83,
    memory: 65,
    bodyType: 20,
    behaviorTrend: 30,
    proactivity: 60,
    knowledgeChannel: 45,
    willPower: 50,
    curiosity: 60,
    analysis: 60,
    emotionality: 30,
    greed: 15,
    libido: 28,
    aggressiveness: 8,
    gaiety: 30,
    moralStandards: 80,
    beauty: 70,
    conception: 22,
    luck: 47,
  },
  delta: {
    power: 2,
    intellect: 2,
    attentiveness: 3,
    learnability: 5,
    agility: 3,
    empathy: 3,
    regeneration: 2,
    health: 2,
    lifespan: 2,
    childhoodLength: 3,
    memory: 5,
    bodyType: 4,
    behaviorTrend: 5,
    proactivity: 8,
    knowledgeChannel: 5,
    willPower: 5,
    curiosity: 5,
    analysis: 5,
    emotionality: 4,
    greed: 7,
    libido: 5,
    aggressiveness: 2,
    gaiety: 5,
    moralStandards: 5,
    beauty: 4,
    conception: 2,
    luck: 2,
  },
};
