import { IRaceDefaults } from '../../interfaces';

export const ELDER_DEFAULTS: IRaceDefaults = {
  value: {
    power: 50,
    intellect: 55,
    attentiveness: 55,
    learnability: 25,
    agility: 55,
    empathy: 50,
    regeneration: 25,
    health: 27,
    lifespan: 12,
    childhoodLength: 25,
    memory: 50,
    bodyType: 40,
    behaviorTrend: 50,
    proactivity: 40,
    knowledgeChannel: 75,
    willPower: 40,
    curiosity: 50,
    analysis: 30,
    emotionality: 35,
    greed: 20,
    libido: 50,
    aggressiveness: 15,
    gaiety: 50,
    moralStandards: 50,
    beauty: 50,
    conception: 33,
    luck: 50,
  },
  delta: {
    power: 2,
    intellect: 2,
    attentiveness: 3,
    learnability: 5,
    agility: 3,
    empathy: 3,
    regeneration: 2,
    health: 2,
    lifespan: 2,
    childhoodLength: 5,
    memory: 5,
    bodyType: 15,
    behaviorTrend: 20,
    proactivity: 10,
    knowledgeChannel: 15,
    willPower: 10,
    curiosity: 15,
    analysis: 20,
    emotionality: 15,
    greed: 7,
    libido: 10,
    aggressiveness: 3,
    gaiety: 15,
    moralStandards: 8,
    beauty: 4,
    conception: 3,
    luck: 2,
  },
};
