import { IRaceDefaults } from '../../interfaces';

export const SHIFTER_DEFAULTS: IRaceDefaults = {
  value: {
    power: 30,
    intellect: 75,
    attentiveness: 60,
    learnability: 60,
    agility: 40,
    empathy: 55,
    regeneration: 50,
    health: 10,
    lifespan: 10,
    childhoodLength: 20,
    memory: 75,
    bodyType: 35,
    behaviorTrend: 50,
    proactivity: 40,
    knowledgeChannel: 80,
    willPower: 50,
    curiosity: 70,
    analysis: 50,
    emotionality: 20,
    greed: 20,
    libido: 40,
    aggressiveness: 10,
    gaiety: 40,
    moralStandards: 50,
    beauty: 75,
    conception: 30,
    luck: 46,
  },
  delta: {
    power: 2,
    intellect: 2,
    attentiveness: 2,
    learnability: 2,
    agility: 2,
    empathy: 2,
    regeneration: 2,
    health: 2,
    lifespan: 2,
    childhoodLength: 2,
    memory: 2,
    bodyType: 2,
    behaviorTrend: 2,
    proactivity: 2,
    knowledgeChannel: 2,
    willPower: 2,
    curiosity: 2,
    analysis: 2,
    emotionality: 2,
    greed: 2,
    libido: 2,
    aggressiveness: 2,
    gaiety: 2,
    moralStandards: 2,
    beauty: 2,
    conception: 2,
    luck: 2,
  },
};
