import { IRaceDefaults } from '../../interfaces';

export const FACESTEALER_DEFAULTS: IRaceDefaults = {
  value: {
    power: 30,
    intellect: 60,
    attentiveness: 60,
    learnability: 60,
    agility: 40,
    empathy: 55,
    regeneration: 50,
    health: 15,
    lifespan: 15,
    childhoodLength: 23,
    memory: 75,
    bodyType: 35,
    behaviorTrend: 50,
    proactivity: 40,
    knowledgeChannel: 80,
    willPower: 50,
    curiosity: 70,
    analysis: 50,
    emotionality: 22,
    greed: 17,
    libido: 50,
    aggressiveness: 9,
    gaiety: 50,
    moralStandards: 45,
    beauty: 70,
    conception: 30,
    luck: 48,
  },
  delta: {
    power: 0,
    intellect: 0,
    attentiveness: 0,
    learnability: 0,
    agility: 0,
    empathy: 0,
    regeneration: 0,
    health: 0,
    lifespan: 0,
    childhoodLength: 0,
    memory: 0,
    bodyType: 0,
    behaviorTrend: 0,
    proactivity: 0,
    knowledgeChannel: 0,
    willPower: 0,
    curiosity: 0,
    analysis: 0,
    emotionality: 0,
    greed: 0,
    libido: 0,
    aggressiveness: 0,
    gaiety: 0,
    moralStandards: 0,
    beauty: 0,
    conception: 0,
    luck: 0,
  },
};
