import { IRaceDefaults } from '../../interfaces';

export const NORD_DEFAULTS: IRaceDefaults = {
  value: {
    power: 60,
    intellect: 60,
    attentiveness: 50,
    learnability: 40,
    agility: 35,
    empathy: 40,
    regeneration: 15,
    health: 20,
    lifespan: 10,
    childhoodLength: 30,
    memory: 35,
    bodyType: 70,
    behaviorTrend: 60,
    proactivity: 70,
    knowledgeChannel: 65,
    willPower: 70,
    curiosity: 25,
    analysis: 40,
    emotionality: 25,
    greed: 15,
    libido: 50,
    aggressiveness: 15,
    gaiety: 55,
    moralStandards: 65,
    luck: 50,
  },
  delta: {
    power: 2,
    intellect: 2,
    attentiveness: 3,
    learnability: 5,
    agility: 3,
    empathy: 3,
    regeneration: 2,
    health: 2,
    lifespan: 2,
    childhoodLength: 5,
    memory: 5,
    bodyType: 15,
    behaviorTrend: 20,
    proactivity: 10,
    knowledgeChannel: 15,
    willPower: 10,
    curiosity: 15,
    analysis: 20,
    emotionality: 15,
    greed: 5,
    libido: 15,
    aggressiveness: 3,
    gaiety: 15,
    moralStandards: 7,
    luck: 2,
  },
};
