import { IRaceDefaults } from '../../interfaces';

export const SINIE_DEFAULTS: IRaceDefaults = {
  value: {
    power: 40,
    intellect: 75,
    attentiveness: 60,
    learnability: 30,
    agility: 45,
    empathy: 50,
    regeneration: 20,
    health: 25,
    lifespan: 15,
    childhoodLength: 50,
    memory: 40,
    bodyType: 30,
    behaviorTrend: 40,
    proactivity: 50,
    knowledgeChannel: 35,
    willPower: 60,
    curiosity: 40,
    analysis: 50,
    emotionality: 35,
    greed: 25,
    libido: 30,
    aggressiveness: 10,
    gaiety: 45,
    moralStandards: 70,
    luck: 50,
  },
  delta: {
    power: 2,
    intellect: 2,
    attentiveness: 3,
    learnability: 5,
    agility: 3,
    empathy: 3,
    regeneration: 2,
    health: 2,
    lifespan: 2,
    childhoodLength: 5,
    memory: 5,
    bodyType: 15,
    behaviorTrend: 20,
    proactivity: 10,
    knowledgeChannel: 15,
    willPower: 10,
    curiosity: 15,
    analysis: 20,
    emotionality: 15,
    greed: 7,
    libido: 10,
    aggressiveness: 2,
    gaiety: 15,
    moralStandards: 7,
    luck: 2,
  },
};
