import { ICommonParameters } from '../interfaces';

export const COMMON_PARAMS_KEYS: Array<keyof ICommonParameters> = [
  'power',
  'intellect',
  'attentiveness',
  'learnability',
  'agility',
  'empathy',
  'regeneration',
  'health',
  'lifespan',
  'childhoodLength',
  'memory',
  'bodyType',
  'behaviorTrend',
  'proactivity',
  'knowledgeChannel',
  'willPower',
  'curiosity',
  'analysis',
  'emotionality',
  'greed',
  'libido',
  'aggressiveness',
  'gaiety',
  'moralStandards',
  'beauty',
  'luck',
];
